### PR TITLE
Upgrade the build chain and fix some minor build issues

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
Full mvn clean install package site works but I haven't tested locally yet as I'm still waiting to get a token (I think)

**Comment by tveronezi** [comment]
@karianna you can grab a personal token https://github.com/settings/tokens

**Comment by exabrial** [comment]
@tveronezi I pulled his branch and ran it locally. If you're ok with the code changes I'll certify that it runs.

**Comment by karianna** [comment]
Hi all, got my token access working, I can confirm the site looks good to me locally.

**Pull request merged**
